export {default as Navbar} from './Navbar/Navbar.jsx'
export {default as Movies} from './Movies/Movies.jsx'
export {default as Profie} from './Profile/Profile.jsx'
export {default as Actor} from './Actors/Actor.jsx'
export {default as MovieDetail} from './MovieDetail/MovieDetai.jsx'